### ISSUE TITLE
Unable to run pdoc from command line

### ISSUE THREAD

**Issue by sindrehan** [BurntSushi/pdoc#102]
I'm having issues with running pdoc from command line. I installed it with pip, and got no errors. However, when I try to run it I get "No command 'pdoc' found". Is there something that I am missing? 

I'm running Ubuntu 15.10.

**Comment by BurntSushi** [comment]
You probably don't have the path for installed binaries in your `PATH`. It's hard to say where exactly the `pdoc` binary is, since it's so system specific. It's also hard to say because you haven't provided the exact commands you used. For example, did you install with `--user`? In a virtualenv?

**Comment by sindrehan** [comment]
Right, so I did a reinstall with `pip install --system pdoc` and that seems to have cleared it right up. Thanks for the help!
