### ISSUE TITLE
ImportError: No module named request - Not working with python 3.5 & urllib.request

### ISSUE THREAD

**Issue by Manslow** [BurntSushi/pdoc#113]
I've been trying to pdoc a package that imports urllib.request. I'm using python 3.5 which is distributed with urllib.request. I get the following... 

```
Traceback (most recent call last):
  File "/usr/local/bin/pdoc", line 472, in <module>
    module = imp.load_source('__pdoc_file_module__', fp, f)
  File "/Users/essence/PycharmProjects/CommentScraper/scrapers/utils.py", line 2, in <module>
    import urllib.request
ImportError: No module named request
```

I'm new to python but I guess this is related to using python 3.5

**Comment by BurntSushi** [comment]
Beautiful soup is not distributed with Python 3.

Please include the commands you used to install `pdoc`.

**Comment by Manslow** [comment]
I meant to post the same error but for urllib.request. Sorry for the confusion. The bs4 error did go away after installing the module. The urllib.request error is still there and it is included with Python 3.5.

**Comment by BurntSushi** [comment]
Please post the full set of commands you've run, including the ones used for installation.

**Comment by Manslow** [comment]
I downloaded pdoc from here https://pypi.python.org/pypi/pdoc
I then ran sudo python setup.py install to install it
I then ran  pdoc utils.py and got the reported error

**Comment by BurntSushi** [comment]
Please see the README for installation instructions. You should be using `pip install pdoc`.

**Comment by Manslow** [comment]
I followed the INSTALL file documents which says:

It should be as straight-forward as sudo python setup.py install

I just ran pip install proc and got this:

You are using pip version 7.1.0, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Requirement already satisfied (use --upgrade to upgrade): pdoc in /Library/Python/2.7/site-packages

The error still occurs.

**Comment by BurntSushi** [comment]
Looks like there is some confusion in your environment setup. Your error message suggests you installed it for Python 2.7.

**Comment by Manslow** [comment]
Ah, good catch. I just used `pip3.5 install pdoc ` and pdoc succesfully installed for python 3.5. 

Now if I type `which pdoc` I get /Library/Frameworks/Python.framework/Versions/3.5/bin/pdoc.

However, I still get the error.

**Comment by BurntSushi** [comment]
I don't know, sorry. If you're getting the same error then you probably aren't running it with Python 3. Even if you weren't, `pdoc` works on Python 2.7 too, so there shouldn't be a problem. There appears to be something wrong with your environment and I don't know how to debug it. The next thing I'd suggest is installing it into a virtualenv.

**Comment by Manslow** [comment]
I managed to get it working with virtualenv. pdoc is a very helpful tool indeed.
