### ISSUE TITLE
can not generate modules documentation of package

### ISSUE THREAD

**Issue by michalseidl** [BurntSushi/pdoc#124]
Hello,
I am not sure if I am missing something obvious but I can not generate documentation of simple package `a` with two modules `b,c` in this form:
```
a/
  __init__.py
  b.py
  c.py
```
When the file __init__.py is empty with command from above dir `a`
`pdoc --html --html-dir ../ --all-submodules a`
no documentation is generated except __init__.py file itself although the parameter --all-submodules is used. I have finally have to modify __init__.py and instert into it
```
import b
import c
__all__ = ['b','c']
```
which I actually do need just for `pdoc` to work

Thanks for any advice Michal S.

**Comment by BurntSushi** [comment]
That's intentional. pdoc is a tool for documenting the **public** interface of your library.

**Comment by stevebrasier** [comment]
See https://github.com/BurntSushi/pdoc/issues/127#issuecomment-332761265

**Comment by michalseidl** [comment]
I see, Thanks
