### ISSUE TITLE
After installing pdoc with pip it not recognised as an executable on Windows

### ISSUE THREAD

**Issue by epogrebnyak** [BurntSushi/pdoc#127]
Tried navigating to \Scripts, same result.

**Comment by BurntSushi** [comment]
I don't understand Python on Windows, so you're probably on your own. I doubt `pdoc` is itself installed as a real executable. Maybe you need to run it with the Python interpreter? e.g., `python path/to/pdoc.py` or `python -m pdoc`?

**Comment by epogrebnyak** [comment]
So far my best case for Windows is below:
1. Download package from Github (e.g. download zip and unpack)
2. In pdoc root directory run ```python setup.py install``` (as described in manual)
3. Use python interpreter to run pdoc:
```python <your python install path>\Scripts\pdoc <package_or_file_path>```

This got ```pdoc``` going for me on Windows.

Remaining question for me: can pdoc document a non-installed package, just a folder with \_\_init\_\_.py inside and several *.py files?  I get an empty listing here:
```
>python D:\Continuum\Anaconda3\Scripts\pdoc kep2
Module kep2
-----------
```

**Comment by stevebrasier** [comment]
I think this is easy to fix; the script pdoc installs just needs to have a .py extension and the user needs to right-click a *.py file and set "open with.." to their Python executable.

**Comment by leonardopsantos** [comment]
This is still broken as of today

```
$ pip install pdoc

$ pdoc
'pdoc' is not recognized as an internal or external command,
operable program or batch file.

$ python -m pdoc
C:\Users\zbhhrc\AppData\Local\Continuum\anaconda3-32\python.exe: No module named pdoc.__main__; 'pdoc' is a package and cannot be directly executed
```

**Comment by mhils** [comment]
@leonardopsantos: Which Python version are you on?

**Comment by mhils** [comment]
@leonardopsantos: I assume you're running Python 3.7 or before, which doesn't pick up the latest release (which declares `python_requires=">=3.8"`).
I've just pushed a pdoc 0.4 release without this dependency which just prints a user-friendly error. Thanks for the feedback!

**Comment by leonardopsantos** [comment]
Hey! Many thanks! Yes, I was indeed using Python 3.7. I ended up upgrading Python to 3.8, but thanks for the fix!!

**Comment by PySimpleGUI** [comment]
Curious what 3.7 specific feature is being used.  I did a (not very exhaustive but did make the effort) search and didn't find anything with 3.7 except for this Issue.

**Comment by mhils** [comment]
@PySimpleGUI: We don't use any 3.7-specific features, it should work properly on 3.7 as well now. What kind of error are you seeing, and what's your output of `pip freeze`?

**Comment by PySimpleGUI** [comment]
It won't run on 3.6.  Gives an error.  Requires 3.7.  Wondering why.

**Comment by mhils** [comment]
What error message are you seeing on 3.6?

**Comment by PySimpleGUI** [comment]
![image](https://user-images.githubusercontent.com/46163555/109233973-d3f95800-7798-11eb-9e62-8520a30a6049.png)

**Comment by mhils** [comment]
Thanks. This is working as intended. We don't support 3.6 as pdoc heavily relies on (among other things) improvements in the typing module that have been introduced with 3.7.

**Comment by PySimpleGUI** [comment]
Was not saying the code had an error.  I think you answered the question though which is typing.

**Comment by mhils** [comment]
Yeah, I think I misread your initial question, sorry. I tried porting to 3.6 FWIW, but it's quite an undertaking for a release that is EOL at the end of the year. So we stay 3.7 only. :)

**Comment by PySimpleGUI** [comment]
Everything's a tradeoff.  I get about 12% of my users on 3.6 when looking at the PyPI installs.
