### ISSUE TITLE
How to include all the function names in the first page? 

### ISSUE THREAD

**Issue by danyaljj** [BurntSushi/pdoc#130]
I want to make the documentation slightly simpler and everything available in the first page (rather than going through so many links). 
Currently this is what I have: http://cogcomp.cs.illinois.edu/software/doc/sioux/ 
But compare it to pdoc's docs: http://pdoc.burntsushi.net/pdoc  --> in the first page, you can already see the names of all the classes and their functions. How can I do this, without breaking my module structure?

**Comment by BurntSushi** [comment]
> How can I do this, without breaking my module structure?

`pdoc` is designed to document the *public* interface of your Python module. If the public interface includes all of your submodules, then it seems like the generated documentation is correct.

If you instead want functions in your submodules to be shown as part of the top-level module, then you must simply re-export them. e.g., In your `__init__.py`:

```
from sioux.submodule import Foo

__all__ = ['Foo']
```

**Comment by danyaljj** [comment]
Makes sense.
