### ISSUE TITLE
Inheritance across modules doesn't work

### ISSUE THREAD

**Issue by Kobzol** [BurntSushi/pdoc#135]
Hello :-) Pdoc correctly shows inheritance links and copies inherited docstrings for methods in a single module, but when I have classes inherited across modules, it doesn't work.

E.g.:
```python
base.py:
class Base(object):
    def fn(self):
        """doc"""
        pass

derived.py:
from base import Base
class Derived(Base):
    def fn(self):
        pass
```

With this there will be no inheritance link and no inherited docstring. The inheritance chain will be displayed but it won't be clickable.

Is there a way to accomplish this? I'd make a PR if you'd point me in the direction how this could be achieved.
My original motivation was to hide inherited methods that are not overridden, because for classes with many methods they are needlessly displayed in the derived classes and it produces visual clutter.
I added it to pdoc (https://github.com/Kobzol/pdoc/commit/53dfee9c89eff28b79ca8ba70507a2e1d72dfb7f) but then I realized that pdoc already handles inheritance and if it worked across modules it would be much easier and less hacky to do this.

**Comment by BurntSushi** [comment]
pdoc supports cross-module linking by generating stable identifiers and then relying on the pdoc http server to resolve them based on which modules are loaded into memory. Links are [generated in templates](https://github.com/BurntSushi/pdoc/blob/master/pdoc/templates/html.mako#L105-L114) and then [resolving the links is in the server](https://github.com/BurntSushi/pdoc/blob/master/scripts/pdoc#L112-L148).

I don't know why this isn't already working, so you'll need to investigate. There may be dragons lurking.

**Comment by Kobzol** [comment]
I wanted to generate a static documentation, so I'm using `--html` generation and thus the dynamic .ext links will not work. I'll try to see if I can resolve the module names during the generation.

**Comment by BurntSushi** [comment]
@Kobzol Sadly, you're shit-out-of-luck. :-) Cross linking isn't supported in the static mode. It's just not a problem I ever tried to solve.

**Comment by Kobzol** [comment]
I looked at how the modules are constructed and it would require a substantial rewrite to support this, I probably won't be going into that now. Feel free to merge my commit if you think that the inherited method hiding functionality is useful. Thanks for a quick answer :-)
