### ISSUE TITLE
Documentation for package - can't get it working

### ISSUE THREAD

**Issue by gosakamu** [BurntSushi/pdoc#136]
Hello everyone,
I'm new to using python but nevertheless I'd like to start with documenting the things I do.

Unfortunatly I can't get pdoc working for a package. For testing purposes I created a folder mypackage with an empty `__init.py__` and a file module1.py with following code:
`def demoprint():
print('now in module1!')
`

I'm on Amazon Linux and run pdoc for the package `pdoc mypackage` and it only shows 

```
Module mypackage
----------------
```

If I then do pdoc mypackage\module1.py I got following output.

```
Module module1
--------------
Functions
---------
demoprint()
```

I expected if I do pdoc on the package it would show the module1 and the function underneath. Can you help?

**Comment by BurntSushi** [comment]
Seems to be working as intended to me. pdoc encourages you to be more explicit with your public interface. Try putting your submodule in your `__init__.py`'s `__all__` list.

You can also try using the `--allsubmodules` flag. I would encourage you to read the output of `pdoc --help`.

**Comment by gosakamu** [comment]
Thank you for the feedback. I got it running.
First I customized the __init__.py and then I had to add the path to PYTONPATH.
