### ISSUE TITLE
format :param the_param_name: description correctly

### ISSUE THREAD

**Issue by limchr** [BurntSushi/pdoc#143]
Usually the parameters of a method or function is formatted like this in docstring:

:param the_param_name: description

pdoc is not converting this correctly. Is there a way to display parameters nicely?

Otherwise I really like it, thanks you for creating it!

**Comment by BurntSushi** [comment]
pdoc only supports Markdown.

**Comment by limchr** [comment]
Thanks for replying so fast. So is there a common way to format parameters in markdown or does anyone his own thing?

**Comment by BurntSushi** [comment]
Do your own thing.

**Comment by shayneoneill** [comment]
Is there any chance of getting this issue revisited. The :param name: desc type things are at the very least a defacto standard for docstrings, and the better ides can generate these automatically from function signatures, so having the ability to interpret these would be huge.
