### ISSUE TITLE
Restrict class interface?

### ISSUE THREAD

**Issue by mriehl** [BurntSushi/pdoc#25]
Hi,

Subclassing bloated classes (like `cmd.Cmd`) will result in pdoc showing all methods from the inheritance tree, which is a *lot*.

Is there some kind of `__all__` at the class level to restrict these? The `Cmd` class for example has lots of internal methods that do not begin with underscores, and I would like to omit those from the documentation.

Any ideas how to go about this?

**Comment by BurntSushi** [comment]
Hmm. You can technically achieve your goal today, but it isn't pretty. It's based on this little line at the [end of the docs](http://pdoc.burntsushi.net/pdoc):

> If `__pdoc__[key] = None`, then key will not be included in the public interface of the module.

So if `Cmd` has a member `foo` that you don't want to show up, I think you can do this:

```python
class MyCmd(Cmd):
    __pdoc__['MyCmd.foo'] = None
```

Listing all the fields sucks, so maybe you can do:

```python
class MyCmd(Cmd):
    for field in Cmd.__dict__.keys():
        __pdoc__['Cmd.%s' % field] = None
```

But this isn't pretty. In that light, I think #15 is a duplicate.

**Comment by mriehl** [comment]
Thanks!
It does the job for my use case, so I'll close this in favor of #15 which has more discussion.
