### ISSUE TITLE
Generating documentation for my code only

### ISSUE THREAD

**Issue by Leockard** [BurntSushi/pdoc#31]
I just started using pdoc today after struggling to find a usable automatic documentation tool. So far, so good. My only problem is this: I use wxpython extensively and when pdoc generates documentation from my package, it also includes documentation for code that is part of wx, not part of my code (eg, if my class derives from wx.Window, the documentation includes ALL the methods from wx.Window, not just mine). How can I avoid this?

**Comment by BurntSushi** [comment]
See https://github.com/BurntSushi/pdoc/issues/25

**Comment by Leockard** [comment]
I just found #25 and #15. Thanks!
