### ISSUE TITLE
Mongoengine compatibility

### ISSUE THREAD

**Issue by kengruven** [BurntSushi/pdoc#32]
I'm trying to run pdoc on a program, and for the most part, it works well, except on one module that has mongoengine.Document subclasses.

mongoengine.Document has a class method "objects" so that if you have a class Foo(mongoengine.Document), then Foo.objects is a special "query set" object which can return all objects, or a filtered subset of them (based on subsequent chained methods).

Unfortunately, this doesn't seem to play nice with pdoc, which uses inspect.getmembers() to inspect the class.  A simple example:

    from mongoengine import Document
    class Foo(Document):
        pass
    import inspect
    inspect.getmembers(Foo)

Result: this raises mongoengine.connection.ConnectionError: "You have not defined a default connection".  Running pdoc on this causes the same exception, but with a deeper stack trace.

The pdoc documentation says "If the name is defined in a different module, it is not public", and since the class method "Document.objects" is defined in the mongoengine module, I would expect it not to be part of the "public interface", and thus not be documented by pdoc.  But perhaps I'm misunderstanding.

At least, I'd like to be able to declare a custom blacklist so that it can know to avoid calling getattr(cls, 'objects') on any Document subclasses.

**Comment by TennyZhuang** [comment]
+1

**Comment by TennyZhuang** [comment]
is there a reasonable way to resolve this now?

**Comment by BurntSushi** [comment]
> Result: this raises mongoengine.connection.ConnectionError: "You have not defined a default connection". Running pdoc on this causes the same exception, but with a deeper stack trace.

`pdoc` only works on idiomatic Python modules. Python modules that raise exceptions upon inspection or try to do other weird things like initiate a database connection just from *inspecting a class* aren't something I'm inclined to expend much effort supporting.

> At least, I'd like to be able to declare a custom blacklist so that it can know to avoid calling getattr(cls, 'objects') on any Document subclasses.

The [documentation for `pdoc`](http://pdoc.burntsushi.net/pdoc) includes this:

> If __pdoc__[key] = None, then key will not be included in the public interface of the module.

You can try that, but I don't know if it will actually work in your case.

**Comment by kengruven** [comment]
BurntSushi makes a good point.  I'm withdrawing this request.

**Comment by rahulkp220** [comment]
Facing the same issue sadly.
