### ISSUE TITLE
Mathjax and equations

### ISSUE THREAD

**Issue by vzhong** [BurntSushi/pdoc#34]
Would it be possible to add in a dependency to Mathjax.js so that we can render equations as well?

**Comment by BurntSushi** [comment]
No. I don't want to include elaborate Javascript dependencies for an edge case. But this shouldn't stop you! The nice thing about `pdoc` is that you can modify the HTML template (and view logic) separate from the core `pdoc` code: https://github.com/BurntSushi/pdoc/tree/master/pdoc/templates
