### ISSUE TITLE
code samples inline

### ISSUE THREAD

**Issue by hyukim17** [BurntSushi/pdoc#55]
It seems that writing example code only works at the top level.

For example, #!python gets parsed correctly as part of a module's comments, but is not if it is part of the docstring of a function or class.

**Comment by BurntSushi** [comment]
Seems to be working fine here? http://pdoc.burntsushi.net/nfldb#nfldb.Query

**Comment by hyukim17** [comment]
You are right. I needed to put a carriage return before the #!python tag and also indent with 4 spaces.
