### ISSUE TITLE
select modules to include in index

### ISSUE THREAD

**Issue by hyukim17** [BurntSushi/pdoc#56]
The default html server index, in Python module list, includes all available Python modules. Is there a way to restrict which modules show up here?

**Comment by BurntSushi** [comment]
Yes. Pass the `--only-pypath` option to `pdoc` and set your `PYTHONPATH` environment variable to point to the packages you want documented.

**Comment by hyukim17** [comment]
Got it. I am creating a temporary environment, overwriting PYTHONPATH, and running pdoc within that environment.

**Comment by hyukim17** [comment]
Is there a way to exclude certain modules?

**Comment by BurntSushi** [comment]
Yes. Don't put them in your `PYTHONPATH`.

**Comment by hyukim17** [comment]
What I mean is, what if a folder contains multiple modules?

**Comment by BurntSushi** [comment]
Ah. There is no specific command line flag to hide modules. The standard mode of operating is to have an entry in `PYTHONPATH` for *each* module you want to document. This implies that there is a single module in each of those directories. This works well in practice as a convention because it corresponds precisely to an idiomatic Python package (which usually contains at most one direct sub-directory with an `__init__.py` file).

**Comment by hyukim17** [comment]
ok, understood, I guess it makes more sense for me to clean up my directory structure

**Comment by gvvka0327** [comment]
I tried the suggest to put the modules I want to show up, in PYTHONPATH; no output on the html page

-bash-4.1$ echo $PYTHONPATH
/users/test/system-test/lib

pdoc --http --http-host=<hostname> --only-pypath

**Comment by r2ad** [comment]
This worked well for me:
```
#!/bin/bash
PYTHONPATH=`pwd`
export PYTHONPATH
pdoc --http --only-pypath
```

**Comment by abubelinha** [comment]
> The default html server index, in Python module list, includes all available Python modules. Is there a way to restrict which modules show up here?

I think this issue might be somehow related (in my case I wanted to document a very specific list of .py scripts):
[Inconsistent module names when specifying multiple paths #325](https://github.com/mitmproxy/pdoc/issues/325)
