### ISSUE TITLE
Listing modules in the PYTHONPATH and publishing on httpserver

### ISSUE THREAD

**Issue by gvvka0327** [BurntSushi/pdoc#75]
I configured PYTHONPATH with only one module and used --http command to publish the documentation for this on a server, command as below,

-bash-4.1$ echo $PYTHONPATH
/home/user/test/lib/lib.py

  " pdoc --http --http-host=<hostname> --only-pypath"

when I open the page on the server, it is blank, enclosing screenshot for this, anything wrong in the way I am using pdoc command or is there a issue here...
![screenshot](https://cloud.githubusercontent.com/assets/14827543/11047963/ff78e248-86e9-11e5-96bb-c0e987357e27.png)

**Comment by BurntSushi** [comment]
`PYTHONPATH` should be set to a *directory* that contains modules you want to document. Please see the docs on `PYTHONPATH`: https://docs.python.org/2/using/cmdline.html#envvar-PYTHONPATH
