### ISSUE TITLE
Documenting methods starting with "_" character

### ISSUE THREAD

**Issue by gvvka0327** [BurntSushi/pdoc#77]
I have a class with few methods starting with "_", all those methods were skipped by pdoc in documenting them, like example,

  def _get_msg():
        """
        Returns commit message
        """

def _get_password(username):
        """
        return  password
        """

Consistently all the methods like these in all the modules were skipped... all the getting methods are skipped...
Anything I am missing or is it a bug in pdoc tool ?

**Comment by mjwillson** [comment]
I'm guessing that's intentional, since a _ prefix in python conventionally signifies that something is private / not part of the public API. Hence doesn't make sense to expose in documentation.

**Comment by BurntSushi** [comment]
@mjwillson Is correct. `pdoc` is a tool used to discover public API documentation of a module.

**Comment by bjinwright** [comment]
Could you support a flag to turn this on?

**Comment by mhils** [comment]
@bjinwright: We won't change the current behavior anytime soon. You can check out
https://pdoc.dev/docs/pdoc.html#control-what-is-documented for more details. If you want to document all private members, a custom template like this should work:

```jinja2
{% extends "default/module.html.jinja2" %}

{% macro is_public(doc) %}
    {% if not doc.name.startswith("__") %}
        true
    {% else %}
        {{ default_is_public(doc) }}
    {% endif %}
{% endmacro %}
```
