### ISSUE TITLE
Ability to get documentation without importing code

### ISSUE THREAD

**Issue by ericholscher** [BurntSushi/pdoc#82]
It sounds like a good bit of the infrastructure is already there for getting docs out of python code without importing it. Would it be possible to have this exposed, so that you could get (perhaps more limited) documentation from a file, without requiring it (and all its dependencies) to be importable?

**Comment by ericholscher** [comment]
Sounds like I can do this by setting `import_path` to an empty list.

**Comment by BurntSushi** [comment]
> It sounds like a good bit of the infrastructure is already there for getting docs out of python code without importing it.

Could you explain a bit more what you mean by this? `pdoc` is irrevocably tied to its ability to import the module it is trying to document. Except for reading documentation on variables (which traverses the AST), everything else is done by runtime inspection, which is only possible when the module is imported.

I agree that a tool that generates documentation by only inspecting the AST (without ever importing the module) is useful. However, that tool is not nor will ever be `pdoc`.

**Comment by ericholscher** [comment]
Ah, okay. I just read something along those lines in the docs, and was hopeful. I keep hoping to find something that doesn't import code to be able to generate docs, but it sounds like pdoc isn't it. Thanks for the reply.
