### ISSUE TITLE
Double-backtick links seem broken

### ISSUE THREAD

**Issue by mjwillson** [BurntSushi/pdoc#88]
I'm not sure exactly if/how these were intended to work, but it looks like they're almost managing to do something quite useful. If I have text in docstrings referring to another class in double-backticks, like:

```
see ``foo.bar``
```

In the HTML output I see:

see **\[**foo.bar**\](/foo/bar.m.html)**

on the package pages, or

see **\[**foo.bar**\](/foo.bar.ext)**

on the (sub)module pages. As in, I see the raw markdown for these links, with that bold formatting.

Note the former would be pretty useful if it was an actual link, as it links to the right page!

**Comment by BurntSushi** [comment]
I think this means that Markdown isn't being run on the doc string? Do you observe other formatting not being applied?

**Comment by mjwillson** [comment]
Nope other markdown seems to get processed fine.
And it's quite odd that I see bold formatting on the square-brackets in the raw markdown link. (Also the link target text is in monospace font).

Maybe some transformations are happening in the wrong order somewhere?

**Comment by BurntSushi** [comment]
I'm not sure what the problem is. The call to markdown is pretty vanilla: https://github.com/BurntSushi/pdoc/blob/master/pdoc/templates/html.mako#L62-L72

**Comment by mjwillson** [comment]
Ah, from looking at `linkify`, it looks like this was meant to work with single backticks, and my use of double backticks is screwing it up.

I don't get any linkification with single backticks though.

**Comment by mjwillson** [comment]
I think it might be that this line:
`ident = matched[1:-1]`
https://github.com/BurntSushi/pdoc/blob/master/pdoc/templates/html.mako#L56
isn't needed, which explains why it almost works with an extra level of backticks (they get stripped) but not with single ones as intended (first and last char gets stripped that shouldn't)

**Comment by BurntSushi** [comment]
The regex includes the backticks though, so match group `0` includes them as well.

**Comment by mjwillson** [comment]
Maybe this varies by python version or something?

**Comment by BurntSushi** [comment]
@mjwillson I don't know. I'm afraid you'll need to either do some debugging or provide enough reproduction details such that I can take a look at it. (I'm not sure when that will happen.)

**Comment by mjwillson** [comment]
After investigating a bit more it seems the issue with double backticks is the regex matches the inner backticks, meaning the outer ones are retained around the replacement. After wiping /tmp/pdoc-3.4 I've managed to get it working with single backticks now though, looks like I was getting the old cached version. Sorry!
