### ISSUE TITLE
Option to only output Markdown?

### ISSUE THREAD

**Issue by sanseihappa** [BurntSushi/pdoc#97]
I really like mkdocs.  I really like your pdoc module.  Can I get the best of both by combining with a few commands and invoking pdoc to output markdown instead of HTML?

**Comment by BurntSushi** [comment]
It's the default mode of operation? `pdoc module` will show a plain text view.

**Comment by sanseihappa** [comment]
Hmm, maybe then I'm not invoking properly, because I don't get all the submodules... even invoking with the `--all-submodules`

**Comment by BurntSushi** [comment]
`pdoc` only shows documentation for one module at a time. If you're noticing differences between the HTML and plain text output, then that probably deserve a bug report.

**Comment by sanseihappa** [comment]
The HTML output appears to be recursively constructing the sub-modules.  For example:

```$ pdoc --html example --html-dir html --html-no-source --overwrite
$ ls html/example/ 
index.html  SomeClass1.m.html  SomeClass2.m.html
$ pdoc example
Module example
--------------
This is a fake example package

Sub-modules
-----------
    example.SomeClass1
    example.SomeClass2
```

The fake `example` package is attached.

So, I was expecting the default text output to also include the sub-modules...
[example.tar.gz](https://github.com/BurntSushi/pdoc/files/184688/example.tar.gz)

**Comment by sanseihappa** [comment]
Essentially, for a multi-module package, should there be an `--md` option or something that will output files in a directory similar to the `--html` option?
