### ISSUE TITLE
Indentation of the text output results in mis-rendered HTML

### ISSUE THREAD

**Issue by sanseihappa** [BurntSushi/pdoc#99]
For example, running `pdoc multiprocessing.pool > mpool.md` results in markdown which has indentation that results in code blocks where I believe they are not intended:

Module multiprocessing.pool
---------------------------

Classes
-------
Pool 
    Class which supports an async version of the `apply()` builtin

    Ancestors (in MRO)
    ------------------
    multiprocessing.pool.Pool
    __builtin__.object

    Descendents
    -----------
    multiprocessing.pool.ThreadPool

    Class variables
    ---------------
    Process

    Methods
    -------
    __init__(self, processes=None, initializer=None, initargs=(), maxtasksperchild=None)

    apply(self, func, args=(), kwds={})
        Equivalent of `apply()` builtin

    apply_async(self, func, args=(), kwds={}, callback=None)
        Asynchronous equivalent of `apply()` builtin

    close(self)

    imap(self, func, iterable, chunksize=1)
        Equivalent of `itertools.imap()` -- can be MUCH slower than `Pool.map()`

    imap_unordered(self, func, iterable, chunksize=1)
        Like `imap()` method but ordering of results is arbitrary

    join(self)

    map(self, func, iterable, chunksize=None)
        Equivalent of `map()` builtin

    map_async(self, func, iterable, chunksize=None, callback=None)
        Asynchronous equivalent of `map()` builtin

    terminate(self)

**Comment by BurntSushi** [comment]
`pdoc module` doesn't output Markdown. It outputs plain text.

**Comment by sanseihappa** [comment]
Ok, any objections to adding a markdown format option?

**Comment by BurntSushi** [comment]
@sanseihappa There is the bit-rotted PR #30, but I'm skeptical of adding more features. That particular PR is quite big and has weird things in it (such as trying to read a `mkdocs.yaml` file).

**Comment by sanseihappa** [comment]
@BurntSushi Not attempting anything that broad in scope.  I've plumbed in a `.markdown()` method for the `Module` class and am working on a suitable template.

I imagine though, that there would be a new script option such as `--markdown` or `--md`.  Plus, I will need to reuse and possibly add an alias for `--html-dir` ... something like `--site-dir`?

**Comment by BurntSushi** [comment]
@sanseihappa You might be able to crib the Markdown template from #30.

New options are OK. I like `--markdown` and `--markdown-dir`.
